### ISSUE TITLE
Can't place TNT in region with allow-block-place: [DIRT, GRASS, TNT]

### ISSUE THREAD

**Issue by Pugabyte** [aromaa/WorldGuardExtraFlagsPlugin#12]
I have a region that I want to only allow placing dirt, grass and TNT in. 

![image](http://i.imgur.com/rsHxjfa.png)

I can place dirt and grass just fine, but cannot place TNT. 

[Here's a gif where I try to place dirt, grass, TNT and wool.](http://i.imgur.com/80PpFV8.gif)

Here's my versions
![image](http://i.imgur.com/aE2Qo7H.png)
(I tried updating, but spigot gave me 2.12.1 and the plugin would not build from source, and I didnt have time to fix the pom.)

**Comment by Pugabyte** [comment]
I found time to fix maven and debug locally; I found that the reason is when I place TNT, the block type isn't TNT, it's air. After realizing this was a WorldGuard event, not spigot, I went to the WorldGuard/WorldEdit IRC chat and asked why this is. 
```
16:24	Pugabyte	So I'm trying to work out a bug in WorldGuardExtraFlags; [it's listening to the PlaceBlockEvent here](https://github.com/isokissa3/WorldGuardExtraFlagsPlugin/blob/master/src/main/java/net/goldtreeservers/worldguardextraflags/listeners/BlockListener.java#L51-L89 ) (the worldguard event, not spigot) and i'm setting the flag to only allow the placement of grass, dirt and TNT. Grass and dirt work fine, but when placing TNT, the blocktype (inside the forloop, `block.getType().toString()`) is returning `AIR`, and preventing TNT from being placed. 
16:25	@wizjany	why are you listening to WG events for starters
16:25	Pugabyte	not my plugin
16:26	@wizjany	/shrug
16:26	@wizjany	we use our events how we need them
16:26	@wizjany	they're not really meant for arbitrary external use
```

**Comment by isokissa3** [comment]
Hmh thats funny, the events are public and not private, ig I could try figure out better solution for it
