### ISSUE TITLE
Glide flag no longer working

### ISSUE THREAD

**Issue by s1h4d0w** [aromaa/WorldGuardExtraFlagsPlugin#129]
Using the latest version of the plugin on latest Paper 1.14.4. 

On 1.12.2 the glide flag would prevent and cancel elytra glide in a region. On 1.14.4 it doesn't seem to work anymore, setting it to `deny` and reloading worldguard gives a `[WorldGuard] Failed to parse flag 'glide' with value 'DENY'`, where setting it to `none` doesn't cause an error but also doesn't cancel or prevent elytra flight.

I'm using the plugin for a PVP arena within a survival world. Players can only leave the arena by using `/exit` and staying still for 10 seconds to be teleported out, but without the flag working people can just elytra out of the arena.

**Comment by aromaa** [comment]
Looks like I somehow missed this issue. Anyway, you seem to be on outdated version as this is fixed in 4.1.4. Hopefully you figured that out.
