### ISSUE TITLE
give-effects flag clears all effects when you leave

### ISSUE THREAD

**Issue by bonn2** [aromaa/WorldGuardExtraFlagsPlugin#131]
The documentation says that give-effects will preserve other effects, but clears all of them when you leave instead.

To reproduce:
Create region
Add give-effects flag
Give self potion effect
Enter region
Exit region

**Comment by aromaa** [comment]
Are you teleporting across worlds?

**Comment by bonn2** [comment]
No, just walking in and out of the region

**Comment by aromaa** [comment]
Then that sounds like you issue, make sure you are using 4.1.4
