### ISSUE TITLE
Can't make allow-block-break SUGAR_CANE

### ISSUE THREAD

**Issue by microwin7** [aromaa/WorldGuardExtraFlagsPlugin#134]
[CHAT] This material isn't seen as 'placable block', use alternative id

name: WorldGuard
main: com.sk89q.worldguard.bukkit.WorldGuardPlugin
version: "6.2.1-SNAPSHOT;1703-85693b9"
softdepend: [WorldEdit, CommandBook]

Spigot 1.8.8

**Comment by aromaa** [comment]
As it is saying, you are using the wrong id, its SUGAR_CANE_BLOCK
