### ISSUE TITLE
The keep-exp flag doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [aromaa/WorldGuardExtraFlagsPlugin#137]
If the flag `keep-exp `is set to `true` in a region, you will still lose all exp on death. But if you activate the `keep-inventory true` flag at the same time, the exp-keeping works.

WorldGuard version 7.0.4-SNAPSHOT+2067-91a1494
WorldGuardExtraFlags version 4.1.4
Paper 1.16.1 - 138 
FAWE 1.16-327;aa93f19

**Comment by aromaa** [comment]
Can you make sure this happens without other plugins? If it does, then it sounds like Spigot bug

**Comment by TheoRetisch1** [comment]
It doesn't happen without other plugins! So I have to disable all plugins one by one ooof. Thank you for your help.
