### ISSUE TITLE
spawn flag and respawn-location flag not working

### ISSUE THREAD

**Issue by whyonly8** [aromaa/WorldGuardExtraFlagsPlugin#138]
I used to have a spawn flag on one of my regions so that players would spawn in a specific location when they died. I decided to add extra flags for the glide and keep inventory flags. These ones seem to work fine for my players, but the spawn flag no longer works. They instead respawn at their home (I also use EssentialsX). I tried setting the respawn-location flag too, but that didn't work. I then tried removing the spawn flag and only using the respawn-location one. I ensured that the priority of this region was higher than the global priority. I really appreciate any help.

        min: {x: 439, y: 59, z: 72}
        max: {x: 495, y: 78, z: 132}
        members: {}
        flags:
            exit: deny
            creeper-explosion: deny
            vine-growth: deny
            respawn-location: {world: world, x: 492.5283852959574, y: 63.0, z: 129.6279268138915,
                pitch: 4.491476, yaw: 173.19232}
            block-break: deny
            interact: allow
            glide: DENY
            block-place: deny
        owners: {}
        type: cuboid
        priority: 2

This is currently what the configuration file looks like. I know this issue is not inherently extra flags, but the addition of the plugin messed up the existing flag.

**Comment by aromaa** [comment]
Essentials config option for respawn priority, this is covered in the FAQ.
