### ISSUE TITLE
[Feature] Inventory in region

### ISSUE THREAD

**Issue by BeeFox-sys** [aromaa/WorldGuardExtraFlagsPlugin#139]
Similar to the effects flag, could there perhaps be a flag to indicate if the player should have a separate inventory inside the region?

Once entering a region with this flag, their inventory will be swapped to whatever they had in their inventory when they last left it, and when they leave it it will revert to whatever they had apon entering the region

**Comment by aromaa** [comment]
I don't intend to mess with inventories as this is really risky and can cause many hard bugs with other plugins that manage inventories.
