### ISSUE TITLE
Can't write text on sign

### ISSUE THREAD

**Issue by doitliketyler** [aromaa/WorldGuardExtraFlagsPlugin#141]
Hello. I have a region setup to allow the placement of signs but the players can't actually leave text on the sign. Is this a bug or did I miss something? Thanks in advance.

**Comment by aromaa** [comment]
Sounds like some other plugin interfering. Did you try removing all other plugigns?

**Comment by doitliketyler** [comment]
You were absolutely correct. After testing all the plugins I discovered it was CMI doing this. I've opened a ticket here: https://github.com/Zrips/CMI/issues/4223

Cheers!
