### ISSUE TITLE
respawn flag when dead from void

### ISSUE THREAD

**Issue by 6u5t4v** [aromaa/WorldGuardExtraFlagsPlugin#142]
The respawn flag doesnt get called if the player dies from the void. Probably because the region doesnt cover the void, so is it possible to use the respawn flag when player gets below `y = 0` ?

**Comment by aromaa** [comment]
The respawn flag only effect the player when they are inside a region and as you have noticed you leave the region once you go below y = 0. There's really no way to "fix" this unless you prevent them from leaving the region by using blocks or you could use flag's like teleport-on-entry or teleport-on-exit to handle "death"
