### ISSUE TITLE
The keep-exp flag is not compatible with PerWorldInventory

### ISSUE THREAD

**Issue by TheoRetisch1** [aromaa/WorldGuardExtraFlagsPlugin#153]
The `keep-exp` flag doesn't work together with the PerWorldInventory plugin. If you die in a corresponding region, the EXP are simply reseted. But if the flag `keep-inventory` is active at the same time, the EXP will also be restored.
Since PerWorldInventory is a widely used inventory management plugin, it would be aweseome if you could make it compatible. Of course I also reported the bug at PerWorldInventory (https://github.com/EbonJaeger/perworldinventory-kt/issues/228).

**Steps to reproduce the behavior:**
1. Install Worldguard + WorldguardExtraFlags + PerWorldInventory
2. Create a region.
3. Set the the flag `keep-exp` to true for the region.
4. Die inside the region -> you will lose your EXP
5. Try it without PWI -> you will keep your EXP

**Plugin versions**
PerWorldInventory 2.3.2 (https://github.com/EbonJaeger/perworldinventory-kt)
WorldGuardExtraFlags 4.1.4
Worldguard 7.0.5-SNAPSHOT build 2084

**Server version**
Paper 1.16.4 - 319

**Additional context and logs**
PWI config: https://pastebin.com/nk97p9nY
PWI world settings: https://pastebin.com/iDfFPiQH
There are no errors in the log.

**Comment by aromaa** [comment]
This is a bug on the PerWorldInventory side.

**Comment by TheoRetisch1** [comment]
Fixed in https://www.spigotmc.org/resources/beta-worldguardextraflags-reborn.96894/ 👍
