### ISSUE TITLE
Re-add flags (allow-block-place, allow-block-break, deny-block-place and deny-block-break) under config.

### ISSUE THREAD

**Issue by andrewkm** [aromaa/WorldGuardExtraFlagsPlugin#154]
What was the problem here: "**This update effectively disabled allow-block-place, allow-block-break, deny-block-place and deny-block-break on WG 7 due to it not working as intended in all cases. The flags still work on WG 6 however.**"

We have never had any issues with these flags at all and heavily rely on them.
Can you perhaps add a config option to enable these flags with a warning that in certain scenarios they will not work?

**Comment by aromaa** [comment]
#152
