### ISSUE TITLE
Trigger command-on-entry when joining the game

### ISSUE THREAD

**Issue by TheoRetisch1** [aromaa/WorldGuardExtraFlagsPlugin#156]
The flag command-on-entry is not triggered when a player logs in and arrives in the corresponding region, e.g. by a relog. A teleport into a region works fine, on the other hand. It would be great if the flag would also execute the command when a player joins the game and arrives in the region.

WorldGuardExtraFlags version 4.1.5-SNAPSHOT
WorldGuard version 7.0.5-SNAPSHOT+15a0809
Tuinity-"8056d13" (MC: 1.16.4)

**Comment by TheoRetisch1** [comment]
bump

**Comment by TheoRetisch1** [comment]
The problem still exists, I would be happy about a solution:
Paper-325 (MC: 1.17.1)
WorldGuard version 7.0.7-SNAPSHOT+2156-9b66513
WorldGuardExtraFlags version 4.1.5-SNAPSHOT

**Comment by TheoRetisch1** [comment]
Fixed in https://www.spigotmc.org/resources/beta-worldguardextraflags-reborn.96894/ 👍

**Comment by aromaa** [comment]
Working as intended. This prevents the commands from being triggered when relogging.
