### ISSUE TITLE
Suggestion - GUI creation to allow for flag setting and more

### ISSUE THREAD

**Issue by EchocallingEarth** [aromaa/WorldGuardExtraFlagsPlugin#157]
Implementation of a ingame GUI for setting flags

Instead of via a extensive chat list a GUI would open in which via a few pages an admin could set all required flags by simply clicking on the appropriate flag icon.

GUI icons would have a hoover option that would display the protection said icon is for. Example oak planks in GUI would hoover over and say something like Block Protection (Prevents block placement)

Additionally there could be a shift click on a icon to bring up more information about said protection. As well as a GUI icon for link to WIKI, Spigot Page (for updates ) and Even a About the Dev Icon(giving credit where earned)

I can try to create images to show what I mean if needed. As I believe this would greatly improve the plugin over all and even allow for further WorldGuardExtraFlag options in the future.

**Comment by aromaa** [comment]
I don't intend to alter anything WG related. Also I would expect that working with GUI's would be significantly slower than the command workflow.
