### ISSUE TITLE
command-on-exit is triggered twice

### ISSUE THREAD

**Issue by TheoRetisch1** [aromaa/WorldGuardExtraFlagsPlugin#159]
If you set any command for the command-on-exit flag it will be triggered twice when leaving a region. However, the command-on-entry flag works correctly.

WorldGuardExtraFlags version 4.1.5-SNAPSHOT
WorldGuard version 7.0.5-SNAPSHOT+15a0809
FastAsyncWorldEdit version 1.16-502;efcca5b
git-Tuinity-"cc34294" (MC: 1.16.4)

**Comment by TheoRetisch1** [comment]
Any news on this?

**Comment by TheoRetisch1** [comment]
bump

**Comment by TheoRetisch1** [comment]
This is still a problem, I would appreciate a solution very much :)

**Comment by TheoRetisch1** [comment]
The problem still exists, I would be very happy about a solution:
Paper-325 (MC: 1.17.1)
WorldGuard version 7.0.7-SNAPSHOT+2156-9b66513
WorldGuardExtraFlags version 4.1.5-SNAPSHOT

**Comment by TheoRetisch1** [comment]
Fixed in https://www.spigotmc.org/resources/beta-worldguardextraflags-reborn.96894/ 👍

**Comment by aromaa** [comment]
Was fixed on 71796a1e6e930322bcd7ae89cde05464598c0873
