### ISSUE TITLE
Extra Flags don't affect players with max permissions (*) and ops 

### ISSUE THREAD

**Issue by DarkKingKaanMC** [aromaa/WorldGuardExtraFlagsPlugin#160]
Any extra flags (like applying an effect on region enter) don't apply to anyone with worldguard permissions.
They do apply after a restart, however. After another restart, it's back to "broken". It's a never ending cycle.
Works just fine with all the other players without permissions.

Reproduction steps:
- Install the plugin
- Make a region and set an extra flag (Like a potion effect)
- The flag will affect only the player _without_ the worldguard permissions
- After a restart it will affect all the players
- After another restart it's back to "broken"

I use the latest version of the plugin with the latest Paper with Java 11 on Linux.
Thank you in advance for your help.

**Comment by EpicRealms** [comment]
Experiecing the same problem...

**Comment by ARR4NN** [comment]
> 
> 
> Any extra flags (like applying an effect on region enter) don't apply to anyone with worldguard permissions.
> They do apply after a restart, however. After another restart, it's back to "broken". It's a never ending cycle.
> Works just fine with all the other players without permissions.
> 
> Reproduction steps:
> 
>     * Install the plugin
> 
>     * Make a region and set an extra flag (Like a potion effect)
> 
>     * The flag will affect only the player _without_ the worldguard permissions
> 
>     * After a restart it will affect all the players
> 
>     * After another restart it's back to "broken"
> 
> 
> I use the latest version of the plugin with the latest Paper with Java 11 on Linux.
> Thank you in advance for your help.
 Hello, Sorry for the long wait I found this on the official spigot page 

>>>
Flag is not working:
Make sure you do not have permissions for the following permission node:

worldguard.region.bypass.<world>.<region>.<flag>

Also make sure you have use-player-move-event set to true in WorldGuard config.

Please also note that if you are OP you have all the permissions, meaning that you are bypassing every flag the plugin provides. This can look like the plugin is not working.

Also /rg bypass doesn't work, at least yet.

**Comment by aromaa** [comment]
Working as intended, the permissions are mentioned on the plugin page.

However, there are changes coming in the future.
