### ISSUE TITLE
Using latest dev version of Worldguard, FAWE. Cannot use "allow-block-place" "allow-block-break" flags.

### ISSUE THREAD

**Issue by FourNineRugz** [aromaa/WorldGuardExtraFlagsPlugin#163]
I'm pretty sure my solution is to use normal WorldEdit, but I don't want to obviously because I value FAWEs performance efficiency. Is there a way to be able to use these flags? 

![plugins](https://user-images.githubusercontent.com/17154368/108375188-5c8b5d80-71c7-11eb-9862-76f32ea4969b.JPG)

**Comment by n54b** [comment]
![image](https://user-images.githubusercontent.com/12047619/108559347-82b21a00-72fb-11eb-8680-910a3007e9e4.png)

**Comment by n54b** [comment]
use skript for this its very easy to disable ...

**Comment by FourNineRugz** [comment]
ok how then

**Comment by Phoenix616** [comment]
Any progress on fixing this?

**Comment by Sacryn** [comment]
Would love to get these flags back for WG7, any progress on the issue?

**Comment by OnyxianSoul** [comment]
Feel free to try this fork, it may or may not work with FAWE, but the flags on this fork work on WG7
https://github.com/OnyxianSoul/WorldGuardExtraFlags-1.17

**Comment by aromaa** [comment]
Related #152
