### ISSUE TITLE
WorldEdit for only the region owner

### ISSUE THREAD

**Issue by ghost** [aromaa/WorldGuardExtraFlagsPlugin#167]
Hello,
I very much appreciate your plugin and all of its flags! I noticed that the WorldEdit flag was for **anyone** who had or had no access in that region (Witch is fine). If possible, please add another flag that allows WorldEdit access for only the region owners and members so that they know others with worldedit don't mess with there region. This is a feature I have honestly wanted for like, forever.

**Comment by amalon** [comment]
hi, i'd argue this default is not really fine. it means I can't let people set the worldedit flag themselves because they'll use the /rg info -> [flags] interface and accidentally allow anybody to mess with their regions. Its possible to specify the group manually with a command like:
```
/rg flag -w "world" -g OWNERS region_name worldedit ALLOW
```
and its possible to manually change existing regions that have the wrong group setting by editing the worldguard files (but its very error prone even with regex search & replace).

**Comment by amalon** [comment]
I'm attempting to rebuild with the following patch (which I suspect may be specific to my use case of enabling worldedit permission globally, then disabling worldedit in _global_ region, and allowing players to enable in their own regions):
```diff
diff --git a/WG/src/main/java/net/goldtreeservers/worldguardextraflags/flags/Flags.java b/WG/src/main/java/net/goldtreeservers/worldguardextraflags/flags/Flags.java
index a72118b8ef9c..d77b599b373e 100644
--- a/WG/src/main/java/net/goldtreeservers/worldguardextraflags/flags/Flags.java
+++ b/WG/src/main/java/net/goldtreeservers/worldguardextraflags/flags/Flags.java
@@ -8,6 +8,7 @@ import com.sk89q.worldguard.protection.flags.BooleanFlag;
 import com.sk89q.worldguard.protection.flags.CommandStringFlag;
 import com.sk89q.worldguard.protection.flags.DoubleFlag;
 import com.sk89q.worldguard.protection.flags.LocationFlag;
+import com.sk89q.worldguard.protection.flags.RegionGroup;
 import com.sk89q.worldguard.protection.flags.SetFlag;
 import com.sk89q.worldguard.protection.flags.StateFlag;
 import com.sk89q.worldguard.protection.flags.StringFlag;
@@ -46,7 +47,7 @@ public final class Flags
 	
 	public final static LocationFlag RESPAWN_LOCATION = new LocationFlag("respawn-location");
 	
-	public final static StateFlag WORLDEDIT = new StateFlag("worldedit", true);
+	public final static StateFlag WORLDEDIT = new StateFlag("worldedit", true, RegionGroup.OWNERS);
 	
 	public final static SetFlag<PotionEffect> GIVE_EFFECTS = new SetFlag<PotionEffect>("give-effects", new PotionEffectFlag(null));
 	
```

however I'm having trouble building. Are there build instructions anywhere? I'm trying "mvn verify" but I just get piles of dependency issues.

**Comment by amalon** [comment]
I hate to nag, but is there any chance of this getting fixed? I've attempted to build the plugin on two occasions and given up.
Thanks.

**Comment by aromaa** [comment]
The designed use case was that you can deny WorldEdit access to specific areas so not including any groups by default is correct there. The only reason to use `worldedit allow -g owners/members` is if you chose to to set `worldedit deny` on the global region so you can allow non-staff to use WorldEdit in their own regions. This is a bit more advanced use case and doesn't really play nicely with inexperienced players who aren't familiar how WorldGuard works. Both WorldGuard and WorldEdit are aimed towards staff so protecting against inexperienced players doesn't really fit here.

In the advanced scenario, the regions should be created by default with `worldedit allow -g owners` so players don't need to worry about that. If they would like to downgrade the group to members then I would recommend making separate command to make it more obvious.
