### ISSUE TITLE
Keep-Inventory stopped working

### ISSUE THREAD

**Issue by Pinguinul2** [aromaa/WorldGuardExtraFlagsPlugin#169]
I have a region where keep inventory worked and now it's not working at all :(
[latest.log](https://github.com/aromaa/WorldGuardExtraFlagsPlugin/files/6253154/latest.log)

**Comment by EasyMcCheesy** [comment]
I have the same problem..

**Comment by ryantheleach** [comment]
keepinventory is working for me on 1.18.1, make sure you don't test this as OP, as you will have the bypass permission for keep inventory (non-intuitive I know)
