### ISSUE TITLE
Keep-inventory flag not working

### ISSUE THREAD

**Issue by EasyMcCheesy** [aromaa/WorldGuardExtraFlagsPlugin#170]
Hi!

The Keep-inventory flag was working the first time I set it up, but it's not working anymore?
I don't know if this is a bug, or I have done something wrong. 

I really need it for my Minecraft server, so it had been nice if it was working!

- Adrian H. | EasyMcCheesy

**Comment by ARR4NN** [comment]
> 
> 
> Hi!
> 
> The Keep-inventory flag was working the first time I set it up, but it's not working anymore?
> I don't know if this is a bug, or I have done something wrong.
> 
> I really need it for my Minecraft server, so it had been nice if it was working!
> 
>     * Adrian H. | EasyMcCheesy

Hello ! 

Check that the region still exists and the flag is still set. i also recommend checking their is no overlapping regions. 
Need anymore help lmk

**Comment by ryantheleach** [comment]
keepinventory is working for me on 1.18.1, make sure you don't test this as OP, as you will have the bypass permission for keep inventory (non-intuitive I know)
