### ISSUE TITLE
Console-command-on-exit not working

### ISSUE THREAD

**Issue by hlnebula** [aromaa/WorldGuardExtraFlagsPlugin#174]
console command on exit does not work.￼ I have it set to /clear %username%

**Comment by elaineandsparky** [comment]
I'm getting the same issue. I set a console ci %playername% and gms %playername% command on another region several months ago and that still works fine but can't get it to work now on another region. Command i'm trying to use is ci %playername% but also tried gms and give commands.

command on exit (not console) works but not everyone on my server has the command i want to run so command on exit just says you do not have perms to use that command.

**Comment by OllieJW** [comment]
> I'm getting the same issue. I set a console ci %playername% and gms %playername% command on another region several months ago and that still works fine but can't get it to work now on another region. Command i'm trying to use is ci %playername% but also tried gms and give commands.
> 
> command on exit (not console) works but not everyone on my server has the command i want to run so command on exit just says you do not have perms to use that command.

For a start it is %username% not %playername%
