### ISSUE TITLE
Fly flag not working

### ISSUE THREAD

**Issue by Grallow** [aromaa/WorldGuardExtraFlagsPlugin#175]
When someone has fly enabled they can fly in a region where it is disabled. Even players without bypass.
This used to work then one day it stopped and we cant figure out why... Anyone know what I can do?

**Comment by pthoelken** [comment]
Me to. I've created a region which should fly is disabled. Elytra still work in this area.

**Comment by Jammone** [comment]
maybe I'm late, but the answer is setting glide flag as DENY

**Comment by aromaa** [comment]
Glide flag targets elytra while fly flag targets actual flying.
