### ISSUE TITLE
Some issues with 1.17

### ISSUE THREAD

**Issue by ProfessorZel** [aromaa/WorldGuardExtraFlagsPlugin#179]
Hellow! My fav dev!
I want to bring to your attention, that WorldGuardExtraFlagsPlugin, got some problems with working on 1.17.

When used ether with WE or with FAWE, and WG - it has problems with displaying pages with custom flags, weirdly causing WE/FAWE nullpointing on "gameprofile1 is null" 
`[19:20:25] [Worker-Main-2/ERROR]: Caught exception in thread Thread[Worker-Main-2,4,main]
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getProperties()" because "gameprofile1" is null
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$2(SkullBlockEntity.java:152) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

Also "allow/deny-place/break" flags are disable, as i understand, due to "WG7.isLegacy" as false, how ever there is no good replacement for it, build in WG7.

Would you be grateful to give a comment on presented issues, and even if not doing work yourself, may be you can point a direction towards which to move?

Ty, for your beautiful plugin, i see you are working on sponge rn, so if you can direct me, i can try to fix this under your supervision.

**Comment by ProfessorZel** [comment]
Also as sidenote, Jenkins link is 522-ing.

**Comment by OnyxianSoul** [comment]
I've updated the plugin, please check this repository for more details
https://github.com/OnyxianSoul/WorldGuardExtraFlags-1.17
