### ISSUE TITLE
1.17?

### ISSUE THREAD

**Issue by srnyx** [aromaa/WorldGuardExtraFlagsPlugin#183]
Does the plugin work on/support 1.17.1? If so, can you mark it as compatible with 1.17 on the Spigot page?

**Comment by OnyxianSoul** [comment]
I've updated it. Check this repository for more details
https://github.com/OnyxianSoul/WorldGuardExtraFlags-1.17

**Comment by srnyx** [comment]
> I've updated it. Check this repository for more details
> [OnyxianSoul/WorldGuardExtraFlags-1.17](https://github.com/OnyxianSoul/WorldGuardExtraFlags-1.17)

Why didn't you just fork it and then make a PR?

**Comment by aromaa** [comment]
Because he didn't make any actual changes

**Comment by srnyx** [comment]
> Because he didn't make any actual changes

Oh?

**Comment by OnyxianSoul** [comment]
As srnyx pointed out, I did do some changes.

The reason that i didn't simply fork it on github is that at first i wasn't sure if the code was going to be public or not when i created it, in addition to the fact that the original author was inactive so any pull request wouldn't be accepted.

That said, feel free to make a push request to this repo if you are interested.
