### ISSUE TITLE
Owner's can't build/break/interact on their regions

### ISSUE THREAD

**Issue by AntoBlp** [aromaa/WorldGuardExtraFlagsPlugin#184]
Inside my spawn region I have another region named shop, where a player can get with the ARM plugin.

The player that gets the region is automatically assigned as the owner of the region.

The issue is that even that the flags are all set to default, the owner still cannot build. Also, the priority is set to 100 while the priority of spawn is set to 0.

I don't want to allow the flags because then every player will have access to the region. 
I just want the owner of the region to be able to build/break/chest-access/etc.
![2021-09-10_23 11 47](https://user-images.githubusercontent.com/90479243/132913020-4358c3d3-b031-4a3a-ab23-f5a47803b5a5.png)
![2021-09-10_23 11 59](https://user-images.githubusercontent.com/90479243/132913026-f1141b80-abf9-42f0-8155-351f529c7f97.png)
![2021-09-10_23 12 27](https://user-images.githubusercontent.com/90479243/132913028-fa704b7b-e05d-4eec-beab-93ffda9e648f.png)

**Comment by OnyxianSoul** [comment]
I believe thats due to worldguard , try removing this plugin and try again. You should set the normal worldguard flags for that region to allow building / opening etc
