### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by makcuber** [aromaa/WorldGuardExtraFlagsPlugin#191]
Are there any plans to keep this project updated for 1.16.5 and on-wards? If not can you please mark it as depreciated/abandoned on both the readme and spigot pages?

**Comment by aromaa** [comment]
No, the project has not been abandoned. I just have had no time to improve the plugin itself.

However, I will fix any critical bugs that prevent the plugin from working on new versions. The plugin still runs just fine even without updates being pushed to it.

I do have plans and progress (offline) on making the project code base more clean and dropping support for legacy versions of Minecraft and only support modern versions of WorldGuard and Minecraft moving forward.

**Comment by RehanPlayz** [comment]
> No, the project has not been abandoned. I just have had no time to improve the plugin itself.
> 
> However, I will fix any critical bugs that prevent the plugin from working on new versions. The plugin still runs just fine even without updates being pushed to it.
> 
> I do have plans and progress (offline) on making the project code base more clean and dropping support for legacy versions of Minecraft and only support modern versions of WorldGuard and Minecraft moving forward.

Can you update it to 1.17 pls

**Comment by D3dWiz** [comment]
Or 1.18 ✌🏻

**Comment by RehanPlayz** [comment]
> Or 1.18 ✌🏻

or both

**Comment by aromaa** [comment]
The plugin works just fine on 1.18, theres no need to "update" it

**Comment by srnyx** [comment]
> The plugin works just fine on 1.18, theres no need to "update" it

Can you mark it as compatible on Spigot?

**Comment by aromaa** [comment]
Closing as no action is required.
