### ISSUE TITLE
Is the plugin accepting contributions?

### ISSUE THREAD

**Issue by LoaiDev** [aromaa/WorldGuardExtraFlagsPlugin#193]
A few months ago I created around 6 extra flags that we needed and they didn't exist in the main plugin or this one. They were created specifically for some minigames however I can see them having more uses. If so please let me know because I don't want to spend alot of time refactoring the code to work with this plugin to not get added.
The flags are:
- no-collisions
- console-command-on-death
- command-on-death
- teleport-on-death
- teleport-on-death-health
- health-on-entry
- health-on-exit

**Comment by aromaa** [comment]
Flag for no collision seems to be the only one that could provide some value. Tho it seems like most servers just completely disable it so I'm not sure whatever this is worth it. Tracking issue is #22

Handling death with flags seems a bit too fragile as there are different behaviors you would expect and then theres the plugin incompatibilities. The keep-exp and keep-inventory flags already provide enough headache from bad plugins.

The health ones can be done with the command flags, so those are a bit too specific.

**Comment by Phoenix616** [comment]
> - teleport-on-death

Can already be handled by `respawn-location`. Or do you mean cancelling the death event and instead moving them somewhere else?
