### ISSUE TITLE
Console Commands not working on 1.18

### ISSUE THREAD

**Issue by GazpaNova** [aromaa/WorldGuardExtraFlagsPlugin#194]
As the title states, console commands are not working on 1.18, no idea why. I've tried many things. I've also found inconsistencies with the playsound flag, seemingly working at random.

**Comment by GazpaNova** [comment]
![imagen](https://user-images.githubusercontent.com/53949680/146689473-34a2930d-0be1-4918-8c93-db68025619e7.png)


This is my region's flag config. Notice the string from the playsound flag, and how it should be doing a broadcast/say command from console upon entry and exit. None of those are currently working.

**Comment by PyxGames** [comment]
Same here did you find a fix?

**Comment by mitchngwen** [comment]
Whats the fix?
