### ISSUE TITLE
how to run the plugin on version 1.7.10?

### ISSUE THREAD

**Issue by vanFEK** [aromaa/WorldGuardExtraFlagsPlugin#196]
I want to run this plugin on version 1.7.10. Spent 20 minutes on the Internet searching for worldguard 6.1.2+, but... on 1.7.10 I can't find the version I needed to run. Tried 6.0.0 - I get an error; found 6.1 - also a bug. 
What to do, please tell me?)

**Comment by Phoenix616** [comment]
Unless you manually backport this plugin to a WorldGuard version compatible with such an outdated version that will not be possible.

**Comment by aromaa** [comment]
6.2 still works on 1.7.
