### ISSUE TITLE
Feature Request: Toast Greeting/Farewell

### ISSUE THREAD

**Issue by LcorpOfficial** [aromaa/WorldGuardExtraFlagsPlugin#202]
Providing the option to use toast prompts on entry/exit, with type argument and message. I would like this option as many servers could use this for different reasons, but specifically I would like custom Unicode images to overlay them for location tags on entry. Think how Pokemon games and others do for locations. 

As for implementation in the code, It seems more or less simple enough to add with few possible situations where it could cause conflicts.

![image](https://user-images.githubusercontent.com/73314328/153108847-cca2aceb-5ad1-4db0-86b0-ede8c09d3403.png)

**Comment by aromaa** [comment]
These require adding custom advancements. You can easily also implement this by using the console-command-on-entry flag to grand and revoke them.
