### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by LuluxClient** [aromaa/WorldGuardExtraFlagsPlugin#206]
Hey I noticed that this plugin was taking some of my takes for no reasons, the original worldguard takes less ticks (in some cases, for example on this timing worldguard is bigger) so I find this strange:
https://spark.lucko.me/vgGpDbdiyP

Currently having 300 players, Java 17, PufferFish 1.18.1

**Comment by aromaa** [comment]
Seems normal to me. The plugin is accounting only for about 2% of the load. You can also grab the dev build to reduce that a bit.
