### ISSUE TITLE
Latest changes are broken.

### ISSUE THREAD

**Issue by andrewkm** [aromaa/WorldGuardExtraFlagsPlugin#210]
The changes you made (latest) regarding removing FAWE and ensuring plugin compiles, has now broken several things.
For example, simply using //copy with WorldEdit generates:

https://gist.githubusercontent.com/andrewkm/397654a823c17aed2eec6f784c35f610/raw/dfa218ffe028242d1a9f333bd433de95adf05020/gistfile1.txt

We've updated a fork of our own without any extensive changes, just removed FAWE and fixed compiling, and we do not experience these errors. There is something on your end causing breakage. @aromaa

**Comment by aromaa** [comment]
Lemme know if there are any more issues, I have been wanting to drop all the legacy code for long time. There is also one breaking change related to the weird bypass permission which was removed and now just respects the /rg bypass which was introduced in WG 7.
