### ISSUE TITLE
Plugin still broken. Could not load 'plugins\WorldGuardExtraFlags.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by andrewkm** [aromaa/WorldGuardExtraFlagsPlugin#212]
Plugin is still no good.
https://pastebin.com/raw/840LUbSH

Please do not bump your target version:
https://github.com/aromaa/WorldGuardExtraFlagsPlugin/blob/master/pom.xml#L19

As you are breaking compatibility on Java 8 1.12.2 servers.
We've tested our fork targeting 8 yet compiling on 17 and works fine across all platforms.

**Comment by aromaa** [comment]
I dropped support for WG6 on the same commit as I bumped the Java version. I don't intend on supporting legacy versions from now on. Majority have moved on to modern versions.

**Comment by andrewkm** [comment]
Alright, we'll continue work on our fork in that case. Cheers!
