### ISSUE TITLE
Fly speed issue

### ISSUE THREAD

**Issue by TeoSaloufardos** [aromaa/WorldGuardExtraFlagsPlugin#218]
In 1.17.1 version of my server with worldguard (7.0.5) and WorldGuardExtraFlags plugins all staff could flight in region that  had fly speed 0. Now with new versions for 1.19 (because i am trying to update my server and currently i am running a beta server) , staff cant fly in those areas with fly speed 0.

**Comment by aromaa** [comment]
As the release notes mentioned, the bypass behavior has been changed to respect /rg bypass. If your staff isn't in the bypass mode, they will be effected. If you want the old behavior, you would create a region with `passthrough ALLOW`, set staff group as part of region members and then set the fly-speed 0 flag for NON_MEMBERS

**Comment by TeoSaloufardos** [comment]
I am the owner of the server and I have /rg bypass but still can't fly in the area.

**Comment by aromaa** [comment]
Did you re-enter the region after toggling the bypass?

**Comment by TeoSaloufardos** [comment]
I have always bypass enabled (as default option is enabled in staff)

**Comment by aromaa** [comment]
Looks like those the speed flags are not respecting bypass properly.
