### ISSUE TITLE
Fly Flag not working

### ISSUE THREAD

**Issue by Chris6ix** [aromaa/WorldGuardExtraFlagsPlugin#220]
Hey :)
I have the issue that the fly flag just doesn't work...it's set to `deny` but players can still fly in that region...
I'm using Paper `1.18.2 #386` with Worldguard `7.0.7` and WorldGuardExtraFlags `4.2.0`

**Comment by aromaa** [comment]
If the players can get fly though commands, make sure to also block them. The fly is toggle only when they enter the region.

**Comment by Chris6ix** [comment]
That's the problem...the WG Support of FlyPerms is broken, and the dev is extremely inactive :/ (The plugin doesn't even officially support 1.18...)
And I haven't found another plugin that can manage Fly with permissions...

Is there not somehow the ability to change permissions when a player enters/leaves a WG region?

**Comment by aromaa** [comment]
Why doesn't a command fit your needs? Thats the most easy way to manage these. If you want to deal with permissions, you can use LuckPerms extension for that, https://github.com/LuckPerms/ExtraContexts

**Comment by Chris6ix** [comment]
I want to use permissions because of 2 reasons:
-With the /fly command, fly gets automatically disabled when changing worlds....with permissions it stays on (For the worlds that the permission applies to)
-I have a "free daily fly" of 1 hour on my server, so that players without the MVP+ Rank can also fly a bit...
This obviously needs a timer of 1 hour to automatically disable the fly again (A temporary permission that expires in 1 hour)

I will try that LuckPerms extension though, thanks for the tip :)
