### ISSUE TITLE
(GodMode) Could not pass event PlayerMoveEvent to WorldGuard because "user" is null

### ISSUE THREAD

**Issue by DarkKingKaanMC** [aromaa/WorldGuardExtraFlagsPlugin#221]
Hello,

I'm getting an error spammed in the console saying that it "could not pass event PlayerMoveEvent to WorldGuard because "user" is null".  It appears it's happening when plugin is checking for the GodMode flag. I've deleted all GodMode flags from all regions but it didn't help. I don't know how to reproduce this issue nor what's causing it. Here's the error:
https://pastebin.com/5fifWY9L

I'm using the latest Paper 1.19 with the latest available WorldGuard and WorldGuardExtraFlags.

Thank you in advance for your help.

**Comment by aromaa** [comment]
Was fixed in dc6613f
