### ISSUE TITLE
Command on entry - bypass doesnt work

### ISSUE THREAD

**Issue by AgentPieCZ** [aromaa/WorldGuardExtraFlagsPlugin#224]
- We use Newest test versions of WE, WG, WGExtraFlags
- Paper - newest

When i, with permission "*" come to region, it will anyway apply command on entry
Example :(command on entry: /fly 0) i will come and it will take fly off... completly ignore bypass

**Comment by aromaa** [comment]
The bypass behavior respects /rg bypass. Just to be sure, you are on dev build of WGEF? Because there was a fix for command-on flags related to bypassing.

**Comment by AgentPieCZ** [comment]
Soo, we used test version of WGExtraFlags, but version right before fix :x sorry for interupting you.
