### ISSUE TITLE
Flag for permissions

### ISSUE THREAD

**Issue by LogGits** [aromaa/WorldGuardExtraFlagsPlugin#29]
It would come in handy if we could make a region give temp permission access while in a region. The same goes for negating permissions. E.g. permission to use a command in a specific region or disabling anticheat checks on player in region. Could a useful feature like this be added? Love the plugin keep up the great work!

**Comment by aromaa** [comment]
Closing this as this can solved by using LuckPerms & ExtraContexts addon. I have always been strongly suggesting to use LuckPerms and I don't intend to support other permission plugins.
